server:
  use-forward-headers: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            thumbnailer:
              - uri: http://localhost:6566/
  security:
    oauth2:
      client:
        provider:
          google:
            user-name-attribute: name
        registration:
          #          github:
          #            client-id: ${GITHUB-CLIENT-ID}
          #            client-secret: ${GITHUB-CLIENT-SECRET}
          #            client-name: Github user
          #            provider: github
          #            scope: user
          #            redirect-uri: http://localhost:8080/login/oauth2/code/github
          google:
            client-id: ${GOOGLE-CLIENT-ID:dummy}
            client-secret: ${GOOGLE-CLIENT-SECRET:dummy}
            client-name: Google Account
            provider: google
#            redirect-uri: ${APPLICATION-ROOT-URL:dummy}/login/oauth2/code/google